# Generated by Django 4.2.6 on 2023-10-25 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('character_class', models.CharField(max_length=100)),
                ('generated_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
